import Head from 'next/head'
import Image from 'next/image'

import GlobalStyles from 'styles/globals'
import Navigation from 'components/Navigation/Navigation'

export default function Home() {
  return (
    <>
      <GlobalStyles />
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main>
          <Navigation />
        </main>
      </div>
    </>
  )
}
