import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import NavigationLinks from 'components/Navigation/Navigation'
import HomeLoader from 'components/HomeLoader/HomeLoader'

export default function Home() {
  const [ isLoading, setIsLoading ] = useState(true)
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main>
          {isLoading ?
            <HomeLoader finishLoading={() => setIsLoading(false)} />
            :
            <NavigationLinks />
          }
        </main>
      </div>
    </>
  )
}
